app/models.py
import os
from . import db


base_dir = os.path.dirname(os.path.abspath(__file__))
db_path = os.path.join(base_dir, 'test.sqlite3')


class Ranking(db.Model):
    __tablename__ = 'ranking'

    id = db.Column(db.Integer, primary_key=True)
    movieName = db.Column(db.String(56), nullable=False, index=True)
    movieImgPath = db.Column(db.String(), nullable=True)
    movieDescription = db.Column(db.String(256), nullable=False, index=True)

    def __repe__(self):
        return 'movie:{}, movieimg:{}, movieContent:{}'.format(self.__class__.movieName,
                        self.__class__.movieImgPath, self.movieDescription)


class MovieProfile(db.Model):
    __tablename__ = 'movieProfile'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False, index=True)
    details = db.Column(db.String(256), nullable=False)
    stars = db.Column(db.String(8), nullable=False, index=True)
    director = db.Column(db.String(24), nullable=False)

    def __repe__(self):
        return 'Movie Profile, movieName: {}, movieDetails: {}, movieStars: {}, \
        movieDirector: {}'.format(self.__class__.name, self.__class__.details, self.__class__.stars, self.__class__.director)


class Comments(db.Model):
    __tablename__ = 'movieComments'

    id = db.Column(db.Integer, primary_key=True)
    userName = db.Column(db.String(24), nullable=False, index=True)
    date = db.Column(db.String(24), nullable=True)
    commentDetails = db.Column(db.String(512), nullable=False)

    def __repe__(self):
        return 'Comments, userName: {}, date: {}, commentDetails: {}'.format(self.__class__.userName,
                                                                             self.__class__.date, self.__class__.commentDetails)

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config


bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from datetime import datetime
from flask import render_template, redirect, url_for, request
from . import main

from .. import db
from ..models import Ranking, MovieProfile


@main.route('/', methods=['GET'])
@main.route('/<int:page>', methods=['GET'])
def index(page=1):
    per_page = 8
    ranks = Ranking.query.order_by().paginate(page, per_page, error_out=False)

    return render_template('index.html', ranks=ranks)


@main.route('/details/<int:mid>', methods=['GET'])
def details(mid):
    profile = MovieProfile.query.filter_by(id=mid).first()
    rank = Ranking.query.filter_by(id=mid).first()

    return render_template('details.html', profile=profile, rank=rank)

app/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for
from . import main

from .. import db
from .. import connectdb


@main.route('/', methods=['GET'])
def index():
    return render_template('index.html')

app/templates/details.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{{ profile.name }}</title>

        <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='fonts/flaticon.css') }}" rel="stylesheet">
    </head>
<body style="margin: 100px;">

       <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">Details about {{ profile.name }}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">

            <header class="my-4">
            </header>

            <section class="about-seciton padd-2" style="background-image:url(/static/images/background/bg5.png)">
		    <div class="container">
			    <div class="row">
				    <div class="col-md-6 col-sm-12 col-xs-12">
					    <div class="single-item">
						    <figure class="image-box">
							    <img src="{{ rank.movieImgPath }}" alt="">
						    </figure>
					    </div>
				    </div>

				    <div class="col-md-6 col-sm-12 col-xs-12">
					    <!-- Start single-item -->
					    <div class="single-item style-two">
						    <div class="sec-title">
							    <h2>About  <span>{{ profile.name }}</span></h2>
						    </div>
                            <p>Director:  <b>{{ profile.director }}</b></p>
                            <p>Stars:  <b>{{ profile.stars }}</b></p><br>

						    <p class="style-2">{{ profile.details }}</p>

					    </div>
					    <!-- End single-item -->
				    </div>


			    </div>
		    </div>
	        </section>

        </div>

</body>
</html>

app/templates/index.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>
            Movie Ranking
        </title>

        <link href="{{ url_for('static', filename='css/heroic-features.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    </head>


    <body style="margin-top: 100px;">

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="#">Start Watching</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Page Content -->
        <div class="container">

            <header class="my-4">
            </header>

            <!-- Page Features -->
            <div class="row text-center">


                {% for rank in ranks.items %}

                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100">
                        <img class="card-img-top" src="{{ rank.movieImgPath }}" alt="">
                        <div class="card-body">
                            <h4 class="card-title">{{ rank.movieName }}</h4>
                            <p class="card-text">{{ rank.movieDescription }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{ url_for('main.details', mid=rank.id) }}" class="btn btn-primary">Find Out More!</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->

        {% if ranks.has_prev %}
            <a href="{{ url_for('main.index', page=ranks.prev_num) }}">&lt;&lt; Newer posts</a>
        {% else %}
            &lt;&lt; Newer posts
        {% endif %} |

        {% if ranks.has_next %}
            <a href="{{ url_for('main.index', page=ranks.next_num) }}">Older posts &gt;&gt;</a>
        {% else %}
            Older posts &gt;&gt;
        {% endif %}

        <!-- Footer -->
        <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; test 2019</p>
        </div>
        <!-- /.container -->
        </footer>

    </body>

</html>